use_frameworks!

platform :ios, '9.0'

target 'MainThreadChecker_Example' do
  pod 'MainThreadChecker', :path => '../'

  target 'MainThreadChecker_Tests' do
    inherit! :search_paths

    
  end
end
